### ISSUE TITLE
How to understand the heatmaps?

### ISSUE THREAD

**Issue by paopao-long** [bsun0802/Zero-DCE#10]
ARn,AGn, and ABn represent the averaged best-fitting curve parameter maps of R, G, and B channels, respectively. But I do not understand the heatmaps.For example,For example, the first picture is the result you provided, and the second picture is the result of my training using the culane dataset.
![res_4_outof_82_85_3](https://user-images.githubusercontent.com/59524741/143802991-141029a2-f11c-4aeb-b153-9f8161b3c1ec.jpg)
![res_4_outof_805252228_0535_02400](https://user-images.githubusercontent.com/59524741/143803170-e6665e62-5706-490f-9903-84a781508c08.jpg)

**Comment by bsun0802** [comment]
The heatmap does not mean anything specifically. It's simply the learned coefficient, plotted as image.

I think your question is it does not work well for you image and the blue channel is a bit different from G and R.
My opinion is, the ZeroDCE is unsupervised, therefore if you dataset is biased, for example, a lot of images have low Blue channel, then the trained network will simply enhance blue channel a lot.

This is not my paper. This is my implementation. If you want ask about performance tuning, you might contact the paper author.

If I answered your questions, please close it~

Let me know if you have other questions.
