### ISSUE TITLE
supplementary material

### ISSUE THREAD

**Issue by hongbojia** [bsun0802/Zero-DCE#2]
Thank you for your paper. Your method is very novel, I want to read your paper carefully, so I would like to get your additional material, thank you!

**Comment by bsun0802** [comment]
Hi,

This is not my paper. The author claims to open source the code and all related materials, but in several months later. So this repo is my own implementation/modification based on what have been described in the paper. 

I believe what you are looking for can be found [here](https://li-chongyi.github.io/Proj_Zero-DCE.html). Please give me a start on this repo thanks~haha
