### ISSUE TITLE
where is the pre-training model for folder demo-output/LE_2

### ISSUE THREAD

**Issue by kkzh2313** [bsun0802/Zero-DCE#3]
您好，我发现demo-output/LE_2该文件夹下zero_DCE最终的增强图片效果优于另一个文件夹LE_4所展示的，想问一下LE_2文件夹对应的预训练模型是不是不在train-jobs/ckpt里面？这里的2和4的含义是指LE-curve的迭代次数吗？

**Comment by bsun0802** [comment]
是的，是指 LE-curve 的迭代次数。
但是我后来发现我的这个 LE = 2 的模型，实际上学出来的 结果是 alpha = 1 everywhere, 就是单纯的把所有像素点变亮同等程度, which is less interesting. 

 我还在继续尝试复现文章的结果，之前五月份问的时候，作者说还要几个月才会开源。

Close it if your question is answered, thx. 

===
p.s. 看你的 repo 里面有剑指 offer，请问你最近会秋招或者明年么？如果有的话，可以加个微信互通下求职么，也可以直接搜我领英，Bo Sun, 南加州大学(University of Southern California)的。

**Comment by kkzh2313** [comment]
我看了demo_out里展示的结果里，利用gamma=0.4校正这一常规处理方法所呈现的效果竟然比这深度学习网络学习的好的多（惊讶脸）！？。请问这里的gamma参数您是怎么得到的（就是调参试吗）？
——————
剑指offer是我之前找工作前刷的，我是去年19届毕业的，已经秋招过了。虽然我很渣渣，如果你对国内秋招情况不是很清楚想了解的话，也可以联系我，我邮箱1529723223@qq.com

**Comment by bsun0802** [comment]
gamma correction 的问题是 1. 本身就太亮的地方会过曝 2. 这个深度学习方法理论上可以把太暗的变亮，太亮的变暗，

但是我复现不出文章那种惊艳的结果，作者目前也不开源。这篇文章的亮点是 no-reference，不需要label 哪些图片是太暗哪些是太亮，是完全的 unsupervised learning， 而且训练起来很快。
