### ISSUE TITLE
Custom color constancy is dividing by zero

### ISSUE THREAD

**Issue by AdamJamil** [bsun0802/Zero-DCE#4]
Getting runtime errors - am I perhaps using the wrong dataset? I did download from the SICE link provided. This is occurring in the color_constency_loss3 method

**Comment by bsun0802** [comment]
Hi, I think the dataset is good. There was a bug and I got the bug fixed. Please clone the new repo.

Previous to the fix, there might be zero division in my utils.color_constency_loss3() method. 

Thanks for trying out my implementation of ZeroDCE, please give it a star and I'm still experimenting on improving the results.

**Comment by AdamJamil** [comment]
Hi, thank you for addressing the error. I wanted to discuss this further with you, can you send me an email at adam.a1d0c@gmail.com?
