### ISSUE TITLE
input image size

### ISSUE THREAD

**Issue by kaishijeng** [bsun0802/Zero-DCE#5]
Can input image be any size, like 1920x1080?
Current demo code seems to limit to 500x500
Thanks

**Comment by bsun0802** [comment]
512x512 is simply for demonstration purpose. 
This method works for any input image size, as the model is fully-convolutional. 

You can simply modify `eval.py` and `demo.py` to output or resize to any size you want.

**Comment by kaishijeng** [comment]
Thanks
