### ISSUE TITLE
Did you quantitatively compare the the performance on your dataset?

### ISSUE THREAD

**Issue by YinengXiong** [bsun0802/Zero-DCE#6]
Hello, Great work!
I have a question. 
Did you quantitatively compare the the performance on your dataset like SICE part2 or other dataset, is your reimplementation performance achieve the number which the paper claimed?

**Comment by bsun0802** [comment]
Thanks for you comment. 

Short answer is NO, I did not perform any quantitative evaluation.

==

Reason is that, I'm interested in applying and modifying the algorithm to be applied to a hardware, so I'm only concerned with what is "feels" like to people eyes. 

If you are interested in rigorously evaluating the performance/metrics of the paper, you can find the authors' code and pre-trained model in his repository.

Instead, I do have a bunch of experiments on tuning the balances between the 4 losses and pruning the network to be as small and fast as possible without losing visual quality. Please give my repository a star and contact me bos@usc.edu for details. 😆

**Comment by YinengXiong** [comment]
Thanks a lot!
