### ISSUE TITLE
Tensorflow Implementation

### ISSUE THREAD

**Issue by tuvovan** [bsun0802/Zero-DCE#7]
Hi, 
Thanks for your detailed explanations. I also implemented Tensorflow Version here. 
https://github.com/tuvovan/Zero_DCE_TF
Looks like our interested topics have some crossing lines.

Stay in touch!

Thanks!

**Comment by bsun0802** [comment]
No Problem!

Actually I managed to achieve the same or even better results with 3/7 parameters of the original ZeroDCE!
But it has been applied in one of the product that I'm intern with so I can not open source it for now. 

We can stay in touch! I just stared your project 😊 .
