### ISSUE TITLE
train with my dataset

### ISSUE THREAD

**Issue by YUunicorn9** [bsun0802/Zero-DCE#8]
Thank you for your code. I want use your code to train person re-identification datasets, however,  the image size is not suit. I run the dataset.py, but it didn't respond. I want know how I can train my own dataset. Look forward to your reply.

**Comment by bsun0802** [comment]
The `dataset.py` is for the dataset mentioned in the paper specifically. You need to create whatever you need, prepare your own dataset write your own data loader.

**Comment by YUunicorn9** [comment]
> The `dataset.py` is for the dataset mentioned in the paper specifically. You need to create whatever you need, prepare your own dataset write your own data loader.

Thank you for your reply!
