### ISSUE TITLE
The value of nrow * h + hspace * (nrow - 1)

### ISSUE THREAD

**Issue by Naturallyyeyeye** [bsun0802/Zero-DCE#9]
Thank you for your code. When I just inference with pre-trained model, there is a problem in demo.py line 28. The value of nrow * h + hspace * (nrow - 1) is -8 ,which is not permitted in the code. Can I ask for your help?

**Comment by bsun0802** [comment]
Hi the demo code assumes there are multiple images in the folder. 

The line of code you are mentioning are used to arrange all the results in an image grid. Which is only for display and has nothing to do with the zero-dce functions.

You can simply modify the code logic to suit for your input images.

**Comment by Naturallyyeyeye** [comment]
Thank you very much. The prolem is solved based on your reply.

**Comment by bsun0802** [comment]
Oh really... good.
